[2024-11-13T21:15:49.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-13T21:15:49.557+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_api manual__2024-11-13T21:15:46.838065+00:00 [queued]>
[2024-11-13T21:15:49.571+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_api manual__2024-11-13T21:15:46.838065+00:00 [queued]>
[2024-11-13T21:15:49.572+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-13T21:15:49.592+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_data_from_api> on 2024-11-13 21:15:46.838065+00:00
[2024-11-13T21:15:49.601+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-13T21:15:49.606+0000] {standard_task_runner.py:72} INFO - Started process 84 to run task
[2024-11-13T21:15:49.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_api', 'manual__2024-11-13T21:15:46.838065+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1d9z03fq']
[2024-11-13T21:15:49.613+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask fetch_data_from_api
[2024-11-13T21:15:49.713+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.fetch_data_from_api manual__2024-11-13T21:15:46.838065+00:00 [running]> on host c2607cc168f6
[2024-11-13T21:15:49.843+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T21:15:46.838065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T21:15:46.838065+00:00'
[2024-11-13T21:15:49.844+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-13T21:15:50.433+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-13T21:15:50.444+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-13T21:15:50.444+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_api, run_id=manual__2024-11-13T21:15:46.838065+00:00, execution_date=20241113T211546, start_date=20241113T211549, end_date=20241113T211550
[2024-11-13T21:15:50.490+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-13T21:15:50.533+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-13T21:15:50.535+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
