[2024-11-13T19:48:05.680+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:48:05.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:48:05.693+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:48:05.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:48:05.730+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:48:05.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:48:05.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:48:05.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.144 seconds
[2024-11-13T19:48:36.034+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:48:36.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:48:36.042+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:48:36.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:48:36.060+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:48:36.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:48:36.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:48:36.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2024-11-13T19:49:06.277+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:49:06.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:49:06.284+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:49:06.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:49:06.302+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:49:06.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:49:06.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:49:06.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.067 seconds
[2024-11-13T19:49:37.012+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:49:37.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:49:37.016+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:49:37.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:49:37.023+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:49:37.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:49:37.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:49:37.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2024-11-13T19:50:07.146+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:50:07.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:50:07.150+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:50:07.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:50:07.166+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:50:07.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:50:07.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:50:07.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2024-11-13T19:50:37.272+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:50:37.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:50:37.279+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:50:37.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:50:37.296+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:50:37.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:50:37.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:50:37.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.104 seconds
[2024-11-13T19:51:07.474+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:51:07.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:51:07.478+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:51:07.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:51:07.491+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:51:07.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:51:07.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:51:07.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2024-11-13T19:51:38.465+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:51:38.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:51:38.470+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:51:38.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:51:38.534+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:51:38.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T19:51:38.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:51:38.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.098 seconds
[2024-11-13T19:52:37.712+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:52:37.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:52:37.722+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:52:37.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:52:37.766+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:52:37.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T19:52:37.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:52:37.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2024-11-13T19:53:07.926+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:53:07.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:53:07.931+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:53:07.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:53:07.957+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:53:07.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T19:53:07.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:53:07.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2024-11-13T19:53:38.007+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:53:38.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:53:38.011+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:53:38.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:53:38.031+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:53:38.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T19:53:38.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:53:38.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2024-11-13T19:54:08.229+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:54:08.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:54:08.233+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:54:08.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:54:08.250+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:54:08.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T19:54:08.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:54:08.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2024-11-13T19:54:38.437+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:54:38.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:54:38.442+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:54:38.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:54:38.449+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:54:38.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:54:38.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:54:38.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2024-11-13T19:59:42.175+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag.py
[2024-11-13T19:59:42.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T19:59:42.181+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:59:42.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T19:59:42.192+0000] {logging_mixin.py:190} INFO - [2024-11-13T19:59:42.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T19:59:42.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T19:59:42.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2024-11-13T20:00:12.336+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:00:12.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:00:12.339+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:00:12.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:00:12.348+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:00:12.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:00:12.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:00:12.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2024-11-13T20:00:43.326+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:00:43.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:00:43.330+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:00:43.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:00:43.339+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:00:43.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:00:43.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:00:43.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2024-11-13T20:01:13.652+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:01:13.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:01:13.656+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:01:13.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:01:13.663+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:01:13.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:01:13.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:01:13.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2024-11-13T20:01:44.330+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:01:44.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:01:44.334+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:01:44.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:01:44.348+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:01:44.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:01:44.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:01:44.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2024-11-13T20:02:14.482+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:02:14.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:02:14.487+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:02:14.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:02:14.499+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:02:14.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:02:14.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:02:14.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2024-11-13T20:02:45.552+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:02:45.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:02:45.557+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:02:45.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:02:45.570+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:02:45.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:02:45.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:02:45.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2024-11-13T20:03:15.645+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:03:15.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:03:15.650+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:03:15.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:03:15.657+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:03:15.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:03:15.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:03:15.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2024-11-13T20:03:46.483+0000] {processor.py:186} INFO - Started process (PID=567) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:03:46.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:03:46.488+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:03:46.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:03:46.525+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:03:46.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:03:46.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:03:46.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.074 seconds
[2024-11-13T20:04:16.582+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:04:16.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:04:16.587+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:04:16.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:04:16.606+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:04:16.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:04:16.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:04:16.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2024-11-13T20:04:47.512+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:04:47.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:04:47.517+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:04:47.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:04:47.540+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:04:47.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:04:47.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:04:47.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2024-11-13T20:05:18.344+0000] {processor.py:186} INFO - Started process (PID=765) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:05:18.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:05:18.349+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:05:18.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:05:18.367+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:05:18.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:05:18.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:05:18.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2024-11-13T20:05:49.317+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:05:49.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:05:49.321+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:05:49.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:05:49.339+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:05:49.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:05:49.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:05:49.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2024-11-13T20:06:19.513+0000] {processor.py:186} INFO - Started process (PID=893) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:06:19.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:06:19.519+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:06:19.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:06:19.546+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:06:19.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:06:19.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:06:19.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2024-11-13T20:06:50.592+0000] {processor.py:186} INFO - Started process (PID=957) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:06:50.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:06:50.602+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:06:50.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:06:50.633+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:06:50.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:06:50.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:06:50.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.099 seconds
[2024-11-13T20:07:20.772+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:07:20.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:07:20.776+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:07:20.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:07:20.792+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:07:20.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:07:20.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:07:20.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2024-11-13T20:07:51.399+0000] {processor.py:186} INFO - Started process (PID=1085) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:07:51.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:07:51.403+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:07:51.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:07:51.425+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:07:51.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:07:51.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:07:51.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2024-11-13T20:08:21.859+0000] {processor.py:186} INFO - Started process (PID=1149) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:08:21.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:08:21.864+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:08:21.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:08:21.889+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:08:21.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:08:21.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:08:21.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2024-11-13T20:08:52.188+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:08:52.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:08:52.194+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:08:52.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:08:52.228+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:08:52.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:08:52.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:08:52.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.074 seconds
[2024-11-13T20:09:22.764+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:09:22.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:09:22.769+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:09:22.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:09:22.782+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:09:22.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:09:22.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:09:22.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2024-11-13T20:09:53.031+0000] {processor.py:186} INFO - Started process (PID=1341) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:09:53.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:09:53.037+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:09:53.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:09:53.049+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:09:53.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:09:53.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:09:53.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2024-11-13T20:10:23.323+0000] {processor.py:186} INFO - Started process (PID=1405) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:10:23.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:10:23.327+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:10:23.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:10:23.340+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:10:23.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:10:23.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:10:23.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2024-11-13T20:10:53.851+0000] {processor.py:186} INFO - Started process (PID=1469) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:10:53.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:10:53.855+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:10:53.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:10:53.865+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:10:53.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:10:53.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:10:53.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2024-11-13T20:12:32.914+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:12:32.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:12:32.926+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:12:32.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:12:32.938+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:12:32.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:12:32.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:12:32.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2024-11-13T20:13:03.588+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:13:03.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:13:03.596+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:13:03.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:13:03.613+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:13:03.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:13:03.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:13:03.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.085 seconds
[2024-11-13T20:13:34.079+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:13:34.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:13:34.083+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:13:34.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:13:34.096+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:13:34.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.data.bronze_layer import bronze_layer
ModuleNotFoundError: No module named 'src'
[2024-11-13T20:13:34.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:13:34.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2024-11-13T20:14:04.270+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:14:04.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:14:04.274+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:14:04.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:14:04.314+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:14:04.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:14:04.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:14:04.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.068 seconds
[2024-11-13T20:16:01.743+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:16:01.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:16:01.752+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:16:01.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:16:01.784+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:16:01.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:16:01.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:16:01.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2024-11-13T20:16:32.071+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:16:32.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:16:32.079+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:16:32.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:16:32.117+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:16:32.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:16:32.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:16:32.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2024-11-13T20:17:02.180+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:17:02.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:17:02.187+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:17:02.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:17:02.211+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:17:02.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:17:02.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:17:02.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2024-11-13T20:17:33.057+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:17:33.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:17:33.061+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:17:33.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:17:33.084+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:17:33.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:17:33.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:17:33.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2024-11-13T20:18:03.221+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:18:03.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:18:03.225+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:18:03.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:18:03.248+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:18:03.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:18:03.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:18:03.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2024-11-13T20:18:33.402+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:18:33.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:18:33.407+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:18:33.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:18:33.428+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:18:33.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:18:33.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:18:33.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2024-11-13T20:19:03.792+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:19:03.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:19:03.796+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:19:03.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:19:03.818+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:19:03.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:19:03.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:19:03.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2024-11-13T20:19:34.181+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:19:34.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:19:34.186+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:19:34.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:19:34.215+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:19:34.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:19:34.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:19:34.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2024-11-13T20:20:04.620+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:20:04.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:20:04.625+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:20:04.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:20:04.651+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:20:04.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:20:04.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:20:04.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2024-11-13T20:20:34.959+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:20:34.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:20:34.964+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:20:34.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:20:34.986+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:20:34.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:20:34.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:20:35.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2024-11-13T20:21:05.488+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:21:05.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:21:05.492+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:21:05.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:21:05.512+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:21:05.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:21:05.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:21:05.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2024-11-13T20:21:35.818+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:21:35.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:21:35.822+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:21:35.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:21:35.864+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:21:35.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:21:35.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:21:35.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.073 seconds
[2024-11-13T20:22:06.734+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:22:06.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:22:06.740+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:22:06.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:22:06.773+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:22:06.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:22:06.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:22:06.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2024-11-13T20:25:27.325+0000] {processor.py:186} INFO - Started process (PID=889) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:25:27.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:25:27.330+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:25:27.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:25:27.356+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:25:27.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:25:27.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:25:27.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2024-11-13T20:25:57.507+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:25:57.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:25:57.513+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:25:57.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:25:57.531+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:25:57.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:25:57.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:25:57.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2024-11-13T20:26:27.700+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:26:27.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:26:27.706+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:26:27.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:26:27.731+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:26:27.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:26:27.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:26:27.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2024-11-13T20:26:57.868+0000] {processor.py:186} INFO - Started process (PID=1081) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:26:57.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:26:57.872+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:26:57.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:26:57.896+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:26:57.894+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:26:57.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:26:57.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2024-11-13T20:27:28.416+0000] {processor.py:186} INFO - Started process (PID=1145) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:27:28.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:27:28.422+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:27:28.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:27:28.458+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:27:28.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:27:28.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:27:28.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.081 seconds
[2024-11-13T20:27:58.540+0000] {processor.py:186} INFO - Started process (PID=1209) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:27:58.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:27:58.546+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:27:58.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:27:58.568+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:27:58.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:27:58.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:27:58.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2024-11-13T20:28:29.443+0000] {processor.py:186} INFO - Started process (PID=1273) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:28:29.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:28:29.451+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:28:29.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:28:29.477+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:28:29.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:28:29.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:28:29.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2024-11-13T20:29:00.467+0000] {processor.py:186} INFO - Started process (PID=1337) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:29:00.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:29:00.473+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:29:00.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:29:00.507+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:29:00.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:29:00.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:29:00.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.067 seconds
[2024-11-13T20:47:53.562+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:47:53.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:47:53.573+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:47:53.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:47:53.603+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:47:53.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:47:53.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:47:53.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.098 seconds
[2024-11-13T20:48:24.597+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:48:24.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:48:24.602+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:48:24.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:48:24.624+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:48:24.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:48:24.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:48:24.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2024-11-13T20:48:55.225+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:48:55.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:48:55.233+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:48:55.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:48:55.262+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:48:55.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:48:55.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:48:55.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2024-11-13T20:49:25.314+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:49:25.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:49:25.319+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:49:25.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:49:25.335+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:49:25.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:49:25.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:49:25.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2024-11-13T20:49:55.808+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:49:55.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:49:55.813+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:49:55.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:49:55.839+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:49:55.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:49:55.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:49:55.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2024-11-13T20:50:25.922+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:50:25.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:50:25.927+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:50:25.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:50:25.949+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:50:25.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:50:25.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:50:25.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2024-11-13T20:50:56.572+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:50:56.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:50:56.577+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:50:56.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:50:56.617+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:50:56.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:50:56.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:50:56.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.079 seconds
[2024-11-13T20:51:26.751+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag.py
[2024-11-13T20:51:26.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T20:51:26.759+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:51:26.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T20:51:26.797+0000] {logging_mixin.py:190} INFO - [2024-11-13T20:51:26.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 7, in <module>
    from src.utils.api_client import fetch_breweries_data
  File "/opt/airflow/dags/src/utils/api_client.py", line 2, in <module>
    from fastapi import HTTPException
ModuleNotFoundError: No module named 'fastapi'
[2024-11-13T20:51:26.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-11-13T20:51:26.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.094 seconds
[2024-11-13T21:15:11.226+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag.py
[2024-11-13T21:15:11.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T21:15:11.240+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:11.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T21:15:12.268+0000] {processor.py:925} INFO - DAG(s) 'pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-11-13T21:15:12.557+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.556+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:pipeline
[2024-11-13T21:15:12.577+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.576+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:pipeline
[2024-11-13T21:15:12.590+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.589+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:pipeline
[2024-11-13T21:15:12.601+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.600+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:pipeline
[2024-11-13T21:15:12.611+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.611+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:pipeline
[2024-11-13T21:15:12.623+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.622+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:pipeline
[2024-11-13T21:15:12.635+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.635+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:pipeline
[2024-11-13T21:15:12.636+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.636+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-13T21:15:12.652+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.652+0000] {dag.py:3262} INFO - Creating ORM DAG for pipeline
[2024-11-13T21:15:12.663+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:12.663+0000] {dag.py:4180} INFO - Setting next_dagrun for pipeline to 2024-11-12 00:00:00+00:00, run_after=2024-11-13 00:00:00+00:00
[2024-11-13T21:15:12.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.469 seconds
[2024-11-13T21:15:42.935+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/dag.py
[2024-11-13T21:15:42.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T21:15:42.942+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:42.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T21:15:43.753+0000] {processor.py:925} INFO - DAG(s) 'pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-11-13T21:15:43.772+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:43.772+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-13T21:15:43.791+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:15:43.791+0000] {dag.py:4180} INFO - Setting next_dagrun for pipeline to 2024-11-12 00:00:00+00:00, run_after=2024-11-13 00:00:00+00:00
[2024-11-13T21:15:43.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.882 seconds
[2024-11-13T21:16:14.055+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag.py
[2024-11-13T21:16:14.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-11-13T21:16:14.071+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:16:14.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-11-13T21:16:14.873+0000] {processor.py:925} INFO - DAG(s) 'pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-11-13T21:16:14.895+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:16:14.895+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-13T21:16:14.914+0000] {logging_mixin.py:190} INFO - [2024-11-13T21:16:14.914+0000] {dag.py:4180} INFO - Setting next_dagrun for pipeline to 2024-11-13 00:00:00+00:00, run_after=2024-11-14 00:00:00+00:00
[2024-11-13T21:16:14.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.884 seconds
